### ISSUE TITLE
error: 报错:

### ISSUE THREAD

**Issue by Valien-zhang** [GetuiLaboratory/react-native-getui#36] opened 2019-04-23 10:50 UTC
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/15426034/56575554-90f85780-65f8-11e9-98e0-08732fe4137a.png">

**Comment by chilidoggca** [comment] 2019-04-23 18:52
May be duplicate of: https://github.com/GetuiLaboratory/react-native-getui/issues/31

Use 1.1.25 if you don't need xiaomi push, huawei push, etc.

If you need xiaomi push, huawei push, etc., follow this guide:
https://github.com/GetuiLaboratory/react-native-getui/tree/master/example/RN多厂商

**Comment by Valien-zhang** [comment] 2019-04-24 01:24
ok  .thanks

**Closed** 2019-09-10 02:58 UTC
